export const QUERY_KEYS = {
  GROUP: "GROUP",
  GROUP_MEMBERS: "GROUP_MEMBERS",
  GROUP_EXPENSES: "GROUP_EXPENSES",
  EXPENSE_CATEGORY: "EXPENSE_CATEGORY",
  EXPENSE_BILL: "EXPENSE_BILL",
  GROUP_BALANCE: "GROUP_BALANCE",
  SETTLEMENT: "SETTLEMENT",
  USER_BALANCE_STATS: "USER_BALANCE_STATS",
  USER_SETTLEMENT_STATS: "USER_SETTLEMENT_STATS",
  USER_ACTIVITY: "USER_ACTIVITY",
  USER: "USER",
  SIMPLIFIED_SETTLEMENT: "SIMPLIFIED_SETTLEMENT"
} as const;

export type QUERY_KEYS = (typeof QUERY_KEYS)[keyof typeof QUERY_KEYS];
