# Generated by Django 6.0.7 on 2026-07-30 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_alter_groupmembership_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('usr', 'user'), ('grp', 'group'), ('exp', 'expense'), ('set', 'settlement'), ('pay', 'payment'), ('spl', 'split')], max_length=3)),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('crt', 'create'), ('upd', 'update'), ('del', 'delete')], max_length=3)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='group.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
