# Generated by Django 6.0.7 on 2026-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('crt', 'create'), ('upd', 'update'), ('del', 'delete'), ('joi', 'join')], max_length=3),
        ),
    ]
