# Generated by Django 6.0.7 on 2026-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
