# Generated by Django 6.0.7 on 2026-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
