# Generated by Django 6.0.7 on 2026-07-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='instance_id',
        ),
    ]
