# Generated by Django 6.0.7 on 2026-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activity_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('crt', 'create'), ('upd', 'update'), ('del', 'delete'), ('joi', 'join'), ('lve', 'leave')], max_length=3),
        ),
    ]
