# Generated by Django 6.0.7 on 2026-08-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_action'),
        ('group', '0004_alter_groupmembership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='group.groups'),
        ),
    ]
