# Generated by Django 6.0.7 on 2026-08-02 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_groupmembership_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_user_group_constraint',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_constraint'),
        ),
    ]
