/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardSettlementsIndexRouteImport } from './routes/_dashboard/settlements/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard/profile/index'
import { Route as DashboardGroupIndexRouteImport } from './routes/_dashboard/group/index'
import { Route as DashboardActivityIndexRouteImport } from './routes/_dashboard/activity/index'
import { Route as DashboardGroupPublicGroupIdRouteImport } from './routes/_dashboard/group/$publicGroupId'
import { Route as DashboardGroupAccessDeniedIndexRouteImport } from './routes/_dashboard/group/access-denied/index'
import { Route as AuthJoinGroupPublicGroupIdRouteImport } from './routes/_auth/join.group.$publicGroupId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettlementsIndexRoute =
  DashboardSettlementsIndexRouteImport.update({
    id: '/settlements/',
    path: '/settlements/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGroupIndexRoute = DashboardGroupIndexRouteImport.update({
  id: '/group/',
  path: '/group/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGroupPublicGroupIdRoute =
  DashboardGroupPublicGroupIdRouteImport.update({
    id: '/group/$publicGroupId',
    path: '/group/$publicGroupId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardGroupAccessDeniedIndexRoute =
  DashboardGroupAccessDeniedIndexRouteImport.update({
    id: '/group/access-denied/',
    path: '/group/access-denied/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthJoinGroupPublicGroupIdRoute =
  AuthJoinGroupPublicGroupIdRouteImport.update({
    id: '/join/group/$publicGroupId',
    path: '/join/group/$publicGroupId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/group/$publicGroupId': typeof DashboardGroupPublicGroupIdRoute
  '/activity/': typeof DashboardActivityIndexRoute
  '/group/': typeof DashboardGroupIndexRoute
  '/profile/': typeof DashboardProfileIndexRoute
  '/settlements/': typeof DashboardSettlementsIndexRoute
  '/join/group/$publicGroupId': typeof AuthJoinGroupPublicGroupIdRoute
  '/group/access-denied/': typeof DashboardGroupAccessDeniedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/group/$publicGroupId': typeof DashboardGroupPublicGroupIdRoute
  '/activity': typeof DashboardActivityIndexRoute
  '/group': typeof DashboardGroupIndexRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/settlements': typeof DashboardSettlementsIndexRoute
  '/join/group/$publicGroupId': typeof AuthJoinGroupPublicGroupIdRoute
  '/group/access-denied': typeof DashboardGroupAccessDeniedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/group/$publicGroupId': typeof DashboardGroupPublicGroupIdRoute
  '/_dashboard/activity/': typeof DashboardActivityIndexRoute
  '/_dashboard/group/': typeof DashboardGroupIndexRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/settlements/': typeof DashboardSettlementsIndexRoute
  '/_auth/join/group/$publicGroupId': typeof AuthJoinGroupPublicGroupIdRoute
  '/_dashboard/group/access-denied/': typeof DashboardGroupAccessDeniedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/group/$publicGroupId'
    | '/activity/'
    | '/group/'
    | '/profile/'
    | '/settlements/'
    | '/join/group/$publicGroupId'
    | '/group/access-denied/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/group/$publicGroupId'
    | '/activity'
    | '/group'
    | '/profile'
    | '/settlements'
    | '/join/group/$publicGroupId'
    | '/group/access-denied'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/group/$publicGroupId'
    | '/_dashboard/activity/'
    | '/_dashboard/group/'
    | '/_dashboard/profile/'
    | '/_dashboard/settlements/'
    | '/_auth/join/group/$publicGroupId'
    | '/_dashboard/group/access-denied/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settlements/': {
      id: '/_dashboard/settlements/'
      path: '/settlements'
      fullPath: '/settlements/'
      preLoaderRoute: typeof DashboardSettlementsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/group/': {
      id: '/_dashboard/group/'
      path: '/group'
      fullPath: '/group/'
      preLoaderRoute: typeof DashboardGroupIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/activity/': {
      id: '/_dashboard/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof DashboardActivityIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/group/$publicGroupId': {
      id: '/_dashboard/group/$publicGroupId'
      path: '/group/$publicGroupId'
      fullPath: '/group/$publicGroupId'
      preLoaderRoute: typeof DashboardGroupPublicGroupIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/group/access-denied/': {
      id: '/_dashboard/group/access-denied/'
      path: '/group/access-denied'
      fullPath: '/group/access-denied/'
      preLoaderRoute: typeof DashboardGroupAccessDeniedIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/join/group/$publicGroupId': {
      id: '/_auth/join/group/$publicGroupId'
      path: '/join/group/$publicGroupId'
      fullPath: '/join/group/$publicGroupId'
      preLoaderRoute: typeof AuthJoinGroupPublicGroupIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthJoinGroupPublicGroupIdRoute: typeof AuthJoinGroupPublicGroupIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthJoinGroupPublicGroupIdRoute: AuthJoinGroupPublicGroupIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardGroupPublicGroupIdRoute: typeof DashboardGroupPublicGroupIdRoute
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute
  DashboardGroupIndexRoute: typeof DashboardGroupIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSettlementsIndexRoute: typeof DashboardSettlementsIndexRoute
  DashboardGroupAccessDeniedIndexRoute: typeof DashboardGroupAccessDeniedIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardGroupPublicGroupIdRoute: DashboardGroupPublicGroupIdRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardGroupIndexRoute: DashboardGroupIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSettlementsIndexRoute: DashboardSettlementsIndexRoute,
  DashboardGroupAccessDeniedIndexRoute: DashboardGroupAccessDeniedIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
