# Generated by Django 6.0.7 on 2026-07-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUALLY', 'Equally'), ('AMOUNT', 'Amount'), ('PERCENTAGE', 'Percentage')], default='EQUALLY', max_length=10),
        ),
        migrations.CreateModel(
            name='SplitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_participant_expense', to='expense.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_participant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
