# Generated by Django 6.0.7 on 2026-07-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_split_type_splitparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='description',
        ),
    ]
