# Generated by Django 6.0.7 on 2026-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups_joined',
            field=models.ManyToManyField(through='group.GroupMembership', to='group.groups'),
        ),
    ]
